[project]
name = "cookiecutter-python-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.1"
dependencies = [
    "config>=0.5.1",
    "mypy>=1.15.0",
    "pydantic>=2.11.2",
    "sqlalchemy>=2.0.40",
    "structlog>=25.2.0",
]
